# Generated by Django 3.1.5 on 2021-01-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210114_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_descrption',
            new_name='topic_description',
        ),
    ]
